### ISSUE TITLE
Fails with cryptic error

### ISSUE THREAD

**Issue by marchoeppner** [ExpressionAnalysis/HLAProfiler#1]
Hi,
so I have been trying to get this to work... 

I cannot seem to get past an annoying error though, which unfortunately provides little information for proper debugging. The following error appears immediately:

```
HLAProfiler.pl predict -fq1 data/E00427-L3_S60_L007_R1_001.fastq.gz -fq2 data/E00427-L3_S60_L007_R2_001.fastq.gz -db database -dd /ifs/data/nfs_share/ikmb_repository/software/hlaprofiler/1.0 -r /ifs/data/nfs_share/ikmb_repository/software/hlaprofiler/1.0/database/data/reference/hla.ref.merged.fa
Making directory  ./E00427-L3_S60_L007_R1_001.fastq.gz/filtered...mkdir ./E00427-L3_S60_L007_R1_001.fastq.gz/filtered
DONE
/ifs/data/nfs_share/ikmb_repository/software/kraken/0.10.5b/classify -t 1 -f -x ./E00427-L3_S60_L007_R1_001.fastq.gz/filtered/E00427-L3_S60_L007_R1_001.fastq.gz. -p /ifs/data/nfs_share/ikmb_repository/software/hlaprofiler/1.0/database/taxonomy/divisions.txt -d /ifs/data/nfs_share/ikmb_repository/software/hlaprofiler/1.0/database/database.kdb -n /ifs/data/nfs_share/ikmb_repository/software/hlaprofiler/1.0/database/taxonomy/nodes.dmp -i /ifs/data/nfs_share/ikmb_repository/software/hlaprofiler/1.0/database/database.idx -S -2 data/E00427-L3_S60_L007_R1_001.fastq.gz data/E00427-L3_S60_L007_R2_001.fastq.gz 2>>
sh: -c: row 0: Syntaxfehler beim unerwarteten Wort `newline'
sh: -c: row 0: `/ifs/data/nfs_share/ikmb_repository/software/kraken/0.10.5b/classify -t 1 -f -x ./E00427-L3_S60_L007_R1_001.fastq.gz/filtered/E00427-L3_S60_L007_R1_001.fastq.gz. -p /ifs/data/nfs_share/ikmb_repository/software/hlaprofiler/1.0/database/taxonomy/divisions.txt -d /ifs/data/nfs_share/ikmb_repository/software/hlaprofiler/1.0/database/database.kdb -n /ifs/data/nfs_share/ikmb_repository/software/hlaprofiler/1.0/database/taxonomy/nodes.dmp -i /ifs/data/nfs_share/ikmb_repository/software/hlaprofiler/1.0/database/database.idx -S -2 data/E00427-L3_S60_L007_R1_001.fastq.gz data/E00427-L3_S60_L007_R2_001.fastq.gz 2>>'
Cleaning out intermediate files...DONE
```

And the "sh: -c: Zeile 0: Syntaxfehler beim unerwarteten Wort `newline'" basically means "syntax error at unexpected word "newline".

I first figured something is wrong with classify from Kraken, but running the command separately works just fine (and takes quite a while, so the HLAprofiler script doesnt even seem to be launching it...). With all the sub routines, I cannot really debug this for myself, so maybe it is possible to narrow down what is happening here?

**Comment by ExpressionAnalysis** [comment]
The error is related to the system call ending in "2>>". This should be pointing to a log file or absent and printing to standard error. We are having trouble replicating this error on our systems. Try specifying a log file name using -l option when running HLAProfiler.pl predict and let us know if this resolves the error. Can you also share the exact command you ran one more time?

**Comment by marchoeppner** [comment]
Thanks, this fixes the issue for us. Maybe just add a check that alerts users to the log file being mandatory? 
Closing.
